application: myapp
version: 1
runtime: php
api_version: 1

handlers:
# Serve php scripts.
- url: /
  script: home.php

- url: /(.+\.php)$
  script: \1
  
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
